import Head from "next/head";
import React from "react";

const center = {
    display: "grid",
    placeItems: "center",
    height: "100vh",
};

export default function Home() {
    return (
        <>
            <Head>
                <title>Real time Chatting App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <h1>hello</h1>
        </>
    );
}
